### PR TITLE
Rebase on to CAPO main

### PR DESCRIPTION
**Pull request by mdbooth**
~~This is a rebase on to current upstream CAPO main branch.~~
This is a merge with `ours` strategy of:
* a rebase on to current upstream CAPO main branch
* the previous history

i.e. It is a rebase which also explicitly declares itself a successor to the previous history.

I identified downstream carry patches with:
```
$ git log --no-merges HEAD ^upstream/main
```

There were only 2:
* 2f2caac035ccb97b80e1ce1e428b67feded8d265 (Downstream owners)
* bc3ad00be63298704c4cd40d639378496e43c3e9 (Add OCP CI config)

However, several other patches were also returned which were backports to the upstream release-0.6 branch. We probably should not pull upstream release branches to main, but we will need a strategy for our own release branches.

For now I have renamed all carry patches to have a `CARRY:` prefix and added a couple more to add vendoring.

### CODE REVIEW

**Comment by stephenfin** [comment]
Can't speak to the failing test, but this looks like a straight forward reset to upstream `main`:

```
$ git remote -v
origin  git@github.com:openshift/cluster-api-provider-openstack.git (fetch)
origin  git@github.com:openshift/cluster-api-provider-openstack.git (push)
shiftstack      git@github.com:shiftstack/cluster-api-provider-openstack.git (fetch)
shiftstack      git@github.com:shiftstack/cluster-api-provider-openstack.git (push)
upstream        git@github.com:kubernetes-sigs/cluster-api-provider-openstack.git (fetch)
upstream        git@github.com:kubernetes-sigs/cluster-api-provider-openstack.git (push)
```

```
$ git log shiftstack/capo-v0.8.0 --oneline
5f50f580 (shiftstack/capo-v0.8.0) CARRY: go mod vendor
1415c4d1 CARRY: Don't ignore vendor directories
878a986d CARRY: Add OCP CI config
5ec07227 CARRY: Downstream OWNERS
c73d55dd (upstream/main) Merge pull request #1690 from shiftstack/gitvendoring
...
```

**Review by mandre — COMMENTED** [review]
This is a straight copy of upstream's `main` branch, with openshift's needed commits clearly marked as `CARRY` patches.
```
❯ git log origin/capo-v0.8.0..k8s/main --oneline
(no result)
❯ git log k8s/main..origin/capo-v0.8.0 --oneline
5f50f580 (HEAD, origin/capo-v0.8.0) CARRY: go mod vendor
1415c4d1 CARRY: Don't ignore vendor directories
878a986d CARRY: Add OCP CI config
5ec07227 CARRY: Downstream OWNERS
```

**Comment by mdbooth** [comment]
I thought the test failure was just missing vendoring due to interaction with .gitignore, but it's more than that. I thought I had previously reproduced locally but I wasn't testing properly. To reproduce you need to explicitly set `GOFLAGS`:
```
make test GOFLAGS=-mod=vendor
```

**Review by mandre — COMMENTED** [review]
/lgtm

Looking at the diff between the upstream's `main` branch and this, we only have the necessary openshift bits.
```
$ git diff k8s/main...origin/capo-v0.8.0 --name-only -- . ':!vendor' ':!hack/tools/vendor'
.ci-operator.yaml
.gitignore
Dockerfile.rhel
OWNERS
OWNERS_ALIASES
```

**Comment by mdbooth** [comment]
The setup-envtest failure should be fixed by this upstream PR: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1707

**Pull request merged**
