### PR TITLE
Rename schema group to openshift io

### PR DESCRIPTION
**Pull request by ingvagabund**
**What this PR does / why we need it**:

Rename `openstackproviderconfig.k8s.io` to `openstackproviderconfig.openshift.io`.

All openshift machine types are required to live under .openshift.io group.
The same holds for provider configs/specs which are shipped with openshift by default.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ingvagabund** [comment]
Given the providerspec is encoded through yaml, installer generated provider spec apiversion is ignored. Thus, the group suffix can be changed in parallel: https://github.com/openshift/installer/pull/2152

**Comment by tomassedovic** [comment]
/hold

I'm really sorry about this, the OpenStack deployments (including the `e2e-openstack` job) have been broken by https://github.com/openshift/library-go/pull/500. I'm putting this on hold to prevent merging before we can fully test it.

The fix (https://github.com/openshift/cluster-kube-controller-manager-operator/pull/275) is merged, but we need to wait for a new release image to get created and re-run the e2e test.

The change itself looks good to me.

**Pull request merged**
