### PR TITLE
NO-JIRA: rebase on main

### PR DESCRIPTION
**Pull request by EmilienM**
Manual rebase since the bot failed with a conflict.

### CODE REVIEW

**Comment by EmilienM** [comment]
/hold
this is wrong

**Review by mdbooth — CHANGES_REQUESTED** [review]
We should never rebase on main, right? We should rebase on a release branch.

**Comment by mandre** [comment]
What @mdbooth said. This should be based on v0.10, which is the latest upstream release.
/hold

**Pull request closed without merging**
