### PR TITLE
OSASINFRA-3437: Rebase on CAPO v0.10

### PR DESCRIPTION
**Pull request by mdbooth**
TODO:
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2037

### CODE REVIEW

**Comment by mdbooth** [comment]
See https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/2034. Ideally lets fix this upstream and cherry-pick it downstream.

**Comment by mdbooth** [comment]
I've speculatively cherry-picked https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2037 here in the expectation that it will merge. We should ensure that it does (and re-cherry-pick as required if it doesn't) before merging.

**Comment by mdbooth** [comment]
/test security

Hello? Anybody home?

**Comment by pierreprinetti** [comment]
The security scan succeeds locally.
Thanks @mdbooth for taking care of this.
/lgtm

**Pull request merged**
