### PR TITLE
Bug 1751471: Machine update: create before delete

### PR DESCRIPTION
**Pull request by pierreprinetti**
With this change, the new machine is created first. The desired outcome
is that in case the new machine specification is not valid, its
creation fails and the old one does not get deleted.

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1751471

/cc Fedosin mandre

### CODE REVIEW

**Comment by mandre** [comment]
/hold
/lgtm

Please remove the hold after e2e-openstack job returns successfully.

**Comment by pierreprinetti** [comment]
/hold cancel
:tada:

**Pull request merged**
