### PR TITLE
Bug 2073398: Fix InstanceCreate port & trunk cleanup

### PR DESCRIPTION
**Pull request by EmilienM**
With this change, the port and trunk cleanups are triggered by any
early failure of InstanceCreate.

When InstanceCreate creates ports and if it creates trunks, these
resources will be deleted if any of the next steps fail and cause the
server never to be created.

Note: the trunk will be deleted first, then the ports.

### CODE REVIEW

**Review by mdbooth — COMMENTED** [review]
Approach looks good to me, and is consistent with volume cleanup in this repo, and port and trunk cleanup in upstream CAPO.

Unfortunately, unlike upstream, we don't have any test coverage which can exercise this. It would good to get at least a manual test. I'm not sure it's worth adding downstream tests just for this given that:
* MAPO (4.11+) has this test coverage
* Adding this test coverage was extremely invasive upstream
* It's not super-critical

**Comment by mdbooth** [comment]
For manual test run:
/hold

Feel free to remove this when it's tested.

**Comment by EmilienM** [comment]
/hold cancel
I finally took the time to test it and it worked, see: https://asciinema.org/a/v4CSwYIqNCS393IronhPjJm2d

**Pull request merged**
