### PR TITLE
Fix vendoring

### PR DESCRIPTION
**Pull request by pierreprinetti**
One file in a vendored folder matched an exclude rule in `.gitignore`.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
Is this a follow-up to #123? If so we can probably re-use the same bz. Otherwise we'll need to create one.

**Comment by pierreprinetti** [comment]
> Is this a follow-up to #123

Not a follow-up of that one. I just realised that `go mod vendor && git clean -fdxn` on a clean `master` working directory would report one vendored file. While this can create issues to dependency checksumming, it's not affecting functionality AFAICS.

Do you think we should merge before master opens?

**Comment by mandre** [comment]
If it's not affecting functionality, this can wait until master opens on Fri.

**Review by mandre — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
