### PR TITLE
Merge upstream into main

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by pierreprinetti** [comment]
As discussed with @mdbooth, the result of the unit tests is not reliable.

**Comment by pierreprinetti** [comment]
@mandre @mdbooth would you be OK to release the /hold so that we can merge and test application credentials downstream sooner rather than later?

**Comment by mandre** [comment]
> @mandre @mdbooth would you be OK to release the /hold so that we can merge and test application credentials downstream sooner rather than later?

I brought this up to Matt this morning and it appears the upstream CAPO release may be delayed a little bit due to late bug discovery. So let's bump MAPO twice, once now, and later to align with a stable release.

/hold cancel

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
