### PR TITLE
OCPBUGS-25748: Add Snyk file to exclude vendor directory on scan

### PR DESCRIPTION
**Pull request by racheljpg**
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/label backport-risk-assessed

**Comment by pierreprinetti** [comment]
Not mergeable unilt https://github.com/openshift/cluster-api-provider-openstack/pull/291 is in

**Comment by pierreprinetti** [comment]
This branch is not used in OpenShift. Closing. Thank you!
/close

**Pull request closed without merging**
