### PR TITLE
Bug 1903424: Ensure MAO dependency is up to date to include newest metrics

### PR DESCRIPTION
**Pull request by JoelSpeed**
This updates MAO to the latest version. This should be done periodically to include new updates to the Machine controller code. In particular, this brings in some new metrics that should allow us to debug slow booting machines in the future.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
/lgtm
/approve
/hold until the tests pass

**Comment by pierreprinetti** [comment]
/retest
Does not look like a flake though

**Comment by mandre** [comment]
The ceph cluster for the underlying cloud platform was under maintenance until yesterday, hopefully CI is a bit more reliable now.
/retest

**Comment by JoelSpeed** [comment]
/hold cancel

All tests have passed

**Comment by JoelSpeed** [comment]
(Cancelling hold caused it to retest the openstack E2E 🤔  Weird, but it's required anyway so won't merge till that passes, no hold needed)

**Comment by mandre** [comment]
There seems to be a regression in 4.7 [preventing us to run the e2e-openstack job on MOC](https://bugzilla.redhat.com/show_bug.cgi?id=1907333).

For now, I'm [moving this job to Vexxhost](https://github.com/openshift/release/pull/14303) so that we can merge your patch.

**Pull request merged**
