### PR TITLE
[release-4.4] Bug 1832999: Migrate to MAO

### PR DESCRIPTION
**Pull request by Fedosin**
Cherry-picked from: https://github.com/openshift/cluster-api-provider-openstack/pull/90

### CODE REVIEW

**Comment by mandre** [comment]
Seems like the worker nodes didn't get provisioned:
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-openstack/98/pull-ci-openshift-cluster-api-provider-openstack-release-4.4-e2e-openstack/13

**Comment by bparees** [comment]
@iamemilio this is passing, is it ready to be unheld and cherry pick approved?

**Comment by Fedosin** [comment]
@bparees yes, it's ready to merge... I put the hold to make sure https://github.com/openshift/cluster-api-provider-openstack/pull/102 passes the tests.
It would be really nice if we can merge them together, I mean https://github.com/openshift/cluster-api-provider-openstack/pull/98 and the 4.4 backport of https://github.com/openshift/cluster-api-provider-openstack/pull/102

**Comment by sdodson** [comment]
/hold
unclear to me whether we're saying we need to include #102 in this change in order to prevent regressions or not

**Comment by bparees** [comment]
4.4.z boat is now full so this can be revisited next week i guess.

**Comment by pierreprinetti** [comment]
@Fedosin 
Do you think that the severity of this bug is really "medium"? Is it possible to stand up a 4.4 cluster on OpenStack without this patch?

CC @iamemilio

**Comment by iamemilio** [comment]
Holding until https://bugzilla.redhat.com/show_bug.cgi?id=1848755 is VERIFIED

**Comment by pierreprinetti** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1848755 is verified.

This is ready for the `cherry-pick-approval`! :rocket:

**Pull request merged**
