### PR TITLE
add machine status

### PR DESCRIPTION
**Pull request by FlorinPeter**
**What this PR does / why we need it**:
This PR allows the nodelink-controller to match the machine with the node.

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FlorinPeter** [comment]
@flaper87 can you please check?

**Comment by flaper87** [comment]
@FlorinPeter hi Florin. any reason why you submitted this PR here and not to https://github.com/kubernetes-sigs/cluster-api-provider-openstack ?

We'd like to just take cherry-picks from upstream on this repo rather than doing changes directly.

Let me know if you need help

**Comment by FlorinPeter** [comment]
@flaper87 Well for me it looks like that the upstream is handling the machine status via annotations and the OpenShift way is to use the Machine.Status to carry the information about the addresses and custom machine provider status like the AWSMachineProviderStatus on the OpenShift AWS repository[1]. From my observations it looks like that the AWS repo [2] and the k8s-sigs repo [3] is also no longer in sync.
Currently the nodelink-controller and the machine-approver needs this status information to sync the nodes and to approve pending csr.
For my point of view this PR should merged here as it deals with the Machine objects that are comming from OpenShift.
I also think that the status should be enriched with something like OpenstackMachineProviderStatus to make this even more consistent with the current implementation. 

[1] https://github.com/openshift/cluster-api-provider-aws/blob/master/pkg/actuators/machine/actuator.go#L128
[2] https://github.com/openshift/cluster-api-provider-aws
[3] https://github.com/kubernetes-sigs/cluster-api-provider-aws

**Comment by tomassedovic** [comment]
Thanks, @FlorinPeter! Sorry this took so long.

To explain @flaper87's position here: regardless of what the AWS's codebase is doing, we don't want to diverge from the upstream as much as we possibly can.

Unfortunately, the OpenShift installer does do a few things differently and it seems that in this case, we have to. This change would probably do no harm (so if you are interested in sending it upstream, that would be awesome), but I'm not sure they'd accept it.

In my testing of this, the worker nodes got synced their CSRs approved correctly, but the masters did not. As far as I can tell, this is because the masters already existed, so they never called the actuator's `Create` function, only `Update`. And `updateAnnotation` function never gets called there for some reason.

So this alone does not fix https://github.com/openshift/installer/issues/1467, it's a step in the right direction and it does approve the worker CSRs.

I'm happy to merge this once you fix the gofmt issue.

**Comment by FlorinPeter** [comment]
@tomassedovic thx for checking this PR. I fixed the fmt check and this should pass now.
From my point of view the whole status handling needs some rework. 
I also saw that there are some functions that are currently not called and the util.GetMachineIfExists[1] function from github.com/openshift/cluster-api uses the wrong import/cluster version [2]

[1] https://github.com/openshift/cluster-api-provider-openstack/blob/master/pkg/cloud/openstack/machine/instancestatus.go#L40
[2] https://github.com/openshift/cluster-api/blob/master/pkg/util/util.go#L30

**Comment by ingvagabund** [comment]
> I also saw that there are some functions that are currently not called and the util.GetMachineIfExists[1] function from github.com/openshift/cluster-api uses the wrong import/cluster version [2]

Openshift actuators do not rely on the cluster object. So as long as the cluster object pieces are not used, it will not cause any trouble.

**Pull request merged**
