### PR TITLE
hack: Add verify-vendor.sh

### PR DESCRIPTION
**Pull request by pierreprinetti**
Add a helper script to check that vendoring is not corrupted.

### CODE REVIEW

**Comment by EmilienM** [comment]
> @EmilienM: changing LGTM is restricted to collaborators

bot, you ruined my Monday :(

**Comment by pierreprinetti** [comment]
/hold
Can wait for 4.8

**Review by mandre — APPROVED** [review]
/lgtm
/approve

**Comment by pierreprinetti** [comment]
/lgtm cancel

This is a test

**Comment by mdbooth** [comment]
Pierre said this was good and he's super trustworthy, so this
/lgtm

**Review by mandre — COMMENTED** [review]
/bugzilla refresh
/hold cancel

**Pull request merged**
