### PR TITLE
UPSTREAM 1715: Add server name for the Machine InternalDNS

### PR DESCRIPTION
**Pull request by mdbooth**
For a node to join the cluster, a CSR generated by kubelet with the node name must be approved. The approval happens if the value of the NodeInternalDNS entry on the Machine matches the node name. When using legacy cloud provider the value of that node name is the Server name. This commit ensures the nodes handled with legacy cloud provides get approved by adding the server name to the list of Machine addresses.

(cherry picked from commit de8aaa481fef13c1d2da4b53d52511155a7a810c)

cc @maysamacedo

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
I'm not sure why can't I lgtm. I'm listed in the team https://github.com/openshift/cluster-api-provider-openstack/blob/main/OWNERS_ALIASES

**Comment by mdbooth** [comment]
@mandre Any idea why @MaysaMacedo can't lgtm?

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Comment by mdbooth** [comment]
> > @mandre Any idea why @MaysaMacedo can't lgtm?
> 
> No idea. I see she's in the [OWNERS_ALIASES](https://github.com/openshift/cluster-api-provider-openstack/blob/fc10b68/OWNERS_ALIASES#L4) file so she should be allowed. Perhaps you can't lgtm your own commit?

That wasn't the error message, though. In the kubernetes org it's because you're not a member of the org.

**Pull request merged**
