### PR TITLE
Update and clean machine api dependencies

### PR DESCRIPTION
**Pull request by kwoodson**
**What this PR does / why we need it**:
The machine libraries from machine-api-operator have been moved to openshift/api. This PR removes the circular dependency that existed on the machine-api-operator which also brought in AWS and Azure. These are removed with this work.

**Which issue(s) this PR fixes** 

**Special notes for your reviewer**:
There are zero code updates. This is a library update and a dependency clean up. This simplifies the dependencies, removes circular dependencies, removes AWS/Azure dependencies, and moves the libraries to their correct openshift/api location.

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:
```release-note
machine-api-operator library migration to openshift/api
```

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by iamemilio** [comment]
Thanks, looks good! We can merge this as soon as the tests pass.

**Comment by kwoodson** [comment]
@mandre It appears the e2e-openstack passed but the proxy one failed. From looking at the tests, I don't think this is related.

/test e2e-openstack-proxy

**Comment by EmilienM** [comment]
/hold cancel
failure in proxy job is not related...

**Comment by mandre** [comment]
Ah, interesting, I had the exact same change locally while I was looking a moving CAPO API to openshift/api. Thanks @kwoodson :+1:

**Pull request merged**
