### PR TITLE
Add metrics

### LINKED ISSUE #100: Enable metrics to support updated MAO metrics integration
/kind feature

With recent enablement of metrics (openshift/machine-api-operator#609) it would now rely on an assumption the metrics will be served on port `8083` for the `machine-controller`. This would require to revendor the MAO and enable metrics serving in controller-runtime manager instance.

[A clear and concise description of what you want to happen.]

Expose port `8081` and wire it to metrics serving.

**Anything else you would like to add:**

Example implementation: https://github.com/openshift/cluster-api-provider-aws/pull/324

[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #100 

**Special notes for your reviewer**:

This PR only ensures that build process won't break with latest MAO version, but not implementing collection of API call failures during machine lifetime. Leaving this on maintainers to consider.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Can you please try a `go mod vendor`?

**Comment by pierreprinetti** [comment]
Please squash that horror that I've made; we have to wait for the CI to get back in shape anyway :pray:

**Comment by mandre** [comment]
/approve
/test e2e-openstack

Thanks for the PR @Danil-Grigorev ! We'll merge as soon as our CI shows some green - it's currently having a hard time due to other issues.

**Comment by Danil-Grigorev** [comment]
@pierreprinetti May I get another LGTM? Updated vendor as it was skewed.

**Comment by pierreprinetti** [comment]
Thank you @Danil-Grigorev !

/lgtm
/hold until e2e-openstack passes

Note that the CI is currently unable to complete successfully until https://github.com/openshift/machine-config-operator/pull/1773 merges

**Comment by pierreprinetti** [comment]
@Danil-Grigorev I have created a commit for resolving conflicts. Can you please check and squash? CI is now expected to work, we should be able to merge right away :crossed_fingers:

**Comment by pierreprinetti** [comment]
ugh `cmd/manager/main.go` needs a go fmt

**Comment by Danil-Grigorev** [comment]
@pierreprinetti Should be ok now. I'm not sure why, but the CI is still failing.

**Comment by pierreprinetti** [comment]
Let's see if it's a flake
/retest

**Comment by Danil-Grigorev** [comment]
CI was failing, as the PR https://github.com/openshift/machine-api-operator/pull/608 was missing log error message (fix for that - https://github.com/openshift/machine-api-operator/pull/639), which should have notified about errors getting `infrastructure` resource. I included the missing scheme injection in a1ee52c755d46bf420d05a483e11b24bb63b853d @pierreprinetti Should be green now.

**Pull request merged**
