### PR TITLE
Add ServerGroupID to OpenstackProviderSpec

### PR DESCRIPTION
**Pull request by pierreprinetti**
With this change, it is possible to pass an OpenStack Server Group[1] in
the machine configuration, so that the machine will be assigned to it.

Prerequisite for OSASINFRA-1300 (soft-anti-affinity)

[1]: https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/server-group.html

### CODE REVIEW

**Comment by pierreprinetti** [comment]
oh come on
/test e2e-openstack

**Comment by pierreprinetti** [comment]
/hold
let's use the group name instead.

**Comment by tomassedovic** [comment]
/lgtm
/hold

Feel free to remove the hold once the `e2e-openstack` job passes.

**Comment by pierreprinetti** [comment]
/hold cancel
:dancer:

**Pull request merged**
