### PR TITLE
NO-ISSUE: CARRY: Add DOWNSTREAM_OWNERS

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by mdbooth** [comment]
@mandre You might have to force this in. Any idea how we ended up in this state?

**Review by mandre — COMMENTED** [review]
This is a clean cherry-pick of https://github.com/openshift/cluster-api-provider-openstack/pull/269.

But because of https://github.com/openshift/release/pull/44167, we can no longer merge in release-4.14. This shouldn't be an issue in theory (rational [here](https://github.com/openshift/release/pull/44167#issuecomment-1757122710)) since we have no plans to backport changes to the release-4.14 branch.

Before I approve, and manually forces this in, can you let me know why you think this patch is needed?

**Comment by pierreprinetti** [comment]
This branch is not and never was used in OpenShift.
/close

**Pull request closed without merging**
