### PR TITLE
Bug 1886848: Save status before patching machine annotations

### PR DESCRIPTION
**Pull request by pierreprinetti**

### CODE REVIEW

**Comment by Fedosin** [comment]
/lgtm

it complies with what other platforms have done with their cluster-api: 
https://github.com/openshift/cluster-api-provider-aws/pull/288
https://github.com/openshift/cluster-api-provider-azure/pull/103

**Review by Fedosin — COMMENTED** [review]
/lgtm

**Review by mandre — COMMENTED** [review]
/approve

**Pull request merged**
