### PR TITLE
Bug 1856270: allow users to manually delete machines stuck in crash loop

### PR DESCRIPTION
**Pull request by iamemilio**
machines that fail to provision and cannot be deleted cause CAPO to get stuck in a very specific crash loop. We want to allow users to manually delete the machine when this happens.

### CODE REVIEW

**Comment by iamemilio** [comment]
I dont think we can hit this code block if the machine has been deleted because before we get to this point, we check if the machine exists multiple times (im not sure why its that redundant) and exit the function if it does not. This should only trigger if we check that the machine exists, and it does, then try to delete it and get a "resource not found" error. I think there must be a bug in openstack that causes this case to occur.

**Comment by iamemilio** [comment]
That being said, I have been unable to create a runnable release image for almost a week, and so I cannot really verify any of this.

**Comment by elmiko** [comment]
ack, thanks for the explanation @iamemilio, i can see that this code won't be reached unless the machine is _not_ deleted. it makes sense now.

/lgtm

**Comment by michaelgugino** [comment]
For additional reference, take a look at how we handled this in the GCP provider:

https://github.com/openshift/cluster-api-provider-gcp/blob/master/pkg/cloud/gcp/actuators/machine/reconciler.go#L343

https://github.com/openshift/cluster-api-provider-gcp/blob/46c5454e7175245a35bbdfcde33349da48a00686/pkg/cloud/gcp/actuators/machine/reconciler.go#L314

**Comment by elmiko** [comment]
solid advice, thanks Mike!

**Comment by mandre** [comment]
> /hold
> 
> This patch is not the right approach in a variety of ways.

Not mentioning it's modifying the vendored MAO directly...

Thanks folks for the feedback and pointers to how GCP handles the same issue.

**Comment by elmiko** [comment]
> Not mentioning it's modifying the vendored MAO directly...

ouch. can't believe i missed that =(

**Comment by iamemilio** [comment]
>  Not mentioning it's modifying the vendored MAO directly...

       ouch. can't believe i missed that =(

Me neither haha

**Comment by iamemilio** [comment]
@michaelgugino the issue with this bug is that the machine will show up when we check that it exists, but it will return "404 resource not found" when we try to delete it.

**Comment by iamemilio** [comment]
Considering your comment on the bugzilla, this is not a viable solution.  Closing

**Pull request closed without merging**
