### PR TITLE
Update from kubernetes-sigs/cluster-api-provider-openstack

### PR DESCRIPTION
**Pull request by dulek**
Update from kubernetes-sigs/cluster-api-provider-openstack.

### CODE REVIEW

**Comment by mdbooth** [comment]
@mandre Please could you force-merge or override this test failure?

**Comment by mdbooth** [comment]
For context, the unit tests are failing because the merge pulls in https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1183, which enables envtests. This PR made changes to the `test` target of Makefile to enable these tests. We aren't running this make target, so we don't setup the envtest environment, so the tests fail.

This test failure is just noise and inconvenience right now as:
* The code was tested upstream
* The code is tested downstream in MAPO

I understand there was some reason that `make test` didn't work in downstream prow. My preference would be to disable these tests until we resolve that, otherwise we're potentially going to be chasing our tails keeping these tests working.

**Comment by dulek** [comment]
/override ci/prow/unit

Let's see if this works…?

**Comment by pierreprinetti** [comment]
https://github.com/openshift/release/pull/27640

**Comment by dulek** [comment]
> [openshift/release#27640](https://github.com/openshift/release/pull/27640)

And it's merged, what now? ;)

**Comment by pierreprinetti** [comment]
>And it's merged

It's not :P

**Comment by mdbooth** [comment]
Hmm. How do we make that test no longer required?

**Comment by dulek** [comment]
I'd just try `/lgtm` /`approve` and see if prow updates it.

**Pull request merged**
