### PR TITLE
Bug 1747245: return an error if the cluster name label is incorrect

### PR DESCRIPTION
**Pull request by Fedosin**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1747245

### CODE REVIEW

**Comment by mandre** [comment]
While I agree on the approach, @ingvagabund seems to have a different view on whether an invalid `machine.openshift.io/cluster-api-cluster` label should prevent a node from joining a cluster. I'd like to get his feedback before approving this PR.

**Comment by ingvagabund** [comment]
`machine.openshift.io/cluster-api-cluster` label contains a value that is supposed to be used to tag/label instances created by the actuator in a cloud provider infrastructure. So it's solely up to you to decide if you really want to enforce even the value (e.g. by checking the infrastructure status). We don't do it in any of our actuators. Also, currently the installer does not look for instance based on tags/labels though based on an instance prefix.

**Comment by ingvagabund** [comment]
This is what I did for Azure: https://github.com/openshift/cluster-api-provider-azure/commit/35cc61a8e6081bccfbbd704c2e911d72809b8444

**Comment by mandre** [comment]
/lgtm

@Fedosin I would be nice to be more consistent with how the other actuator tag resources in the future.

**Pull request merged**
