### PR TITLE
CARRY: Fix vendoring

### PR DESCRIPTION
**Pull request by mdbooth**
In separate commits:
* Adds a new `CARRY` verify-vendoring make target which will fail if vendoring is out of date
* Updates vendoring
* Adds new `UPSTREAM` backport of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1707

### CODE REVIEW

**Comment by mdbooth** [comment]
We need https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1707 to fix `test`.

**Comment by mdbooth** [comment]
https://github.com/openshift/release/pull/43982 should prevent us pushing without out-of-date vendoring again.

**Comment by mdbooth** [comment]
Needs https://github.com/openshift/release/pull/43988 to merge first.

**Comment by mdbooth** [comment]
It's still failing due to envtest-setup:
```
make[1]: Leaving directory '/go/src/sigs.k8s.io/cluster-api-provider-openstack/hack/tools'
unable to make sure store is initialized: unable to make sure base binaries dir exists: mkdir /.local: permission denied
KUBEBUILDER_ASSETS="" go test -v ./... 
```

We can see that XDG_DATA_HOME is set correctly, though:
```
XDG_DATA_HOME=/tmp/data
```

**Comment by mandre** [comment]
> We can see that XDG_DATA_HOME is set correctly, though:
> 
> ```
> XDG_DATA_HOME=/tmp/data
> ```

Try `XDG_DATA_HOME=/tmp/.local/share XDG_CACHE_HOME=/tmp/.cache`. This is what I had to do in https://github.com/openshift/release/pull/39007/.

**Comment by mandre** [comment]
> > We can see that XDG_DATA_HOME is set correctly, though:
> > ```
> > XDG_DATA_HOME=/tmp/data
> > ```
> 
> Try `XDG_DATA_HOME=/tmp/.local/share XDG_CACHE_HOME=/tmp/.cache`. This is what I had to do in [openshift/release#39007](https://github.com/openshift/release/pull/39007).

Hmm, re-reading your error message, I'm not sure it's gonna help.

**Comment by mdbooth** [comment]
I've added a DO NOT MERGE patch which hardcodes a value which needs to go into prow once we've worked out what it needs to be.

/hold

**Review by mandre — COMMENTED** [review]
/lgtm
/hold

Pending tests, but tide prevents this PR to merge until tests pass anyway. Feel free to remove the hold when you're happy with CI.

**Comment by mdbooth** [comment]
@mandre For your enjoyment: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-openstack/265/pull-ci-openshift-cluster-api-provider-openstack-main-test/1709939542892482560/artifacts/test/build-log.txt 🍾

**Pull request merged**
