### PR TITLE
UPSTREAM 1696: Add ephemeral storage support to the AdditionalBlockDevices

### PR DESCRIPTION
**Pull request by EmilienM**
Clean backports for `Add ephemeral storage support to the AdditionalBlockDevices`.

### CODE REVIEW

**Comment by mdbooth** [comment]
/hold

This may be ok, but I'd like to think carefully about the implications of unreleased API backports.

**Comment by EmilienM** [comment]
I think we also need to backport the bump of Gophercloud to v1.7.0.

**Comment by EmilienM** [comment]
/hold cancel
Everything was merged upstream. Backports are clean.

**Pull request merged**
