### PR TITLE
Set Filter Types to gophercloud ListOpts

### PR DESCRIPTION
**Pull request by iamemilio**
We created a bunch of redundant structs in the ProviderConfig to be used in place of ListOpts in gophercloud requests. This is unnecessary, clunky, and could break if the ListOpts change in gophercloud. We also caste them to their ListOpts equivalents later on for no good reason. I removed this unnecessary duplication by just using the ListOpts from gophercloud as filters.  

/cc @pierreprinetti

### CODE REVIEW

**Comment by dulek** [comment]
Won't this break API contract? Those ListOpts seem to have different tags - camelCase vs _.

**Comment by iamemilio** [comment]
> Won't this break API contract? Those ListOpts seem to have different tags - camelCase vs _.

Yes, I think it would actually :facepalm:

**Comment by iamemilio** [comment]
> Patches which remove 120 LOCs are normally my thing, but are you sure we can do this?
> 
> My concern is that by doing this we're delegating the api stability of OpenstackProviderSpec to gophercloud. That doesn't sound safe: if they do anything incompatible to those ListOpts then we can't upgrade gophercloud any more, at least not without putting this stuff back. I also doubt our regression suite is comprehensive enough that we'd notice before release.
> 
> The existing solution is ugly and verbose, but it is at least safe.
> 
> Let me know if there are mitigating circumstances, I've completely misunderstood the context, or even just that we do this all the time elsewhere so we're already managing this risk. Until then I'd prefer we
> 
> /hold

The way things stand right now, we are not copying values into gophercloud ListOpt structs to create queries. We are casting the "Filter" structs to their ListOpt counterparts, so we are actually still dependent/breakable by gophercloud changes. Also lol do we even have a regression test for CAPO?

**Pull request closed without merging**
